# Generated by Django 4.2.20 on 2025-04-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_locallegislation_option_response_question_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='locallegislation',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.issue'),
        ),
        migrations.AddField(
            model_name='response',
            name='responce',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
