# Generated by Django 4.2.20 on 2025-04-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_locallegislation_issue_response_responce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='creater',
        ),
    ]
